version: "3.9"

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  webapp:
    restart: always
    build:
      context: ./webapp
    ports:
      - "8000:8000"
    command: [ "python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: ./webapp
    volumes:
      - ./webapp/src/cats:/app/src/cats
    command: ['celery', '--workdir=./src', '-A', 'proj', 'worker' ]

volumes:
  cache:
    driver: local
