version: "3.9"

services:
  redis:
    image: redis
    restart: always

  web:
    build:
      context: .
      dockerfile: ./webapp/Dockerfile
    expose:
      - 8000
    volumes:
      - static_volume:/app/src/static
    entrypoint:
      - ./entrypoint.sh


  nginx:
    build: ./webapp/ngnix
    volumes:
      - static_volume:/app/src/static
    ports:
      - "8000:80"
    depends_on:
      - webapp

  worker:
    restart: always
    build:
      context: ./webapp
    volumes:
      - ./cats:/app/src/cats
    command: ['celery', '--workdir=./src', '-A', 'proj', 'worker' ]

volumes:
  static_volume: