version: "3.9"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: ./webapp
    ports:
      - "8000:8000"
    entrypoint:
      - ./entrypoint.sh

  nginx:
    build: ./src/nginx

    volumes:
      - static_volume:/app/web/staticfiles
      - media_volume:/app/web/mediafiles
    ports:
      - 8000:80
    depends_on:
        - webapp

  worker:
    restart: always
    build:
      context: ./webapp
    volumes:
      - ./cats:/app/src/cats
    command: ['celery', '--workdir=./src', '-A', 'proj', 'worker' ]

volumes:
  static_volume:
  media_volume: