version: "3.9"

services:
  redis:
    image: redis
    restart: always

  webapp:
    build:
      context: ./webapp
      dockerfile: ./Dockerfile
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    entrypoint:
      - ./entrypoint.sh


  nginx:
    build: ./webapp/ngnix
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "8000:80"
    depends_on:
      - webapp


  worker:
    restart: always
    build:
      context: ./webapp
    volumes:
      - ./cats:/app/src/cats
    command: ['celery', '--workdir=./src', '-A', 'proj', 'worker' ]

volumes:
  static_volume:
  media_volume: